Repository Koco12/CloudComputing, pull requests merged in 2019-10, with the labels that each got.

#3 Delete history.html
  history.html
Labels: duplicate

#5 Delete wikipage.css
  wikipage.css
Labels: duplicate

#4 Delete homepage.html
  homepage.html
Labels: duplicate

#11 Pages updated with pictures
  WebPage/architecture.html
  WebPage/characteristics.html
  WebPage/emergingTrends.html
  WebPage/history-1.html
  WebPage/images_alternative/architecture.jpg
  WebPage/images_alternative/characteristics.jpg
  WebPage/images_alternative/frontPage.png
  WebPage/images_alternative/frontPage_hybridcloud.png
  WebPage/images_alternative/frontPage_privatecloud.png
  WebPage/images_alternative/frontPage_publiccloud.png
  WebPage/images_alternative/function.png
  WebPage/images_alternative/history.jpg
  WebPage/images_alternative/history_2.png
  WebPage/images_alternative/history_3.jpg
  WebPage/images_alternative/history_4.jpg
  WebPage/images_alternative/homepage_jumbo.png
  WebPage/images_alternative/mobile.png
  WebPage/images_alternative/placeholder.png
  WebPage/images_alternative/security.png
  WebPage/images_alternative/security1.png
  WebPage/images_alternative/security2.jpg
  WebPage/images_alternative/serverless.png
  WebPage/images_alternative/trends1.png
  WebPage/images_alternative/trends2.png
  WebPage/index.html
  WebPage/security.html
  WebPage/serviceModels.html
  WebPage/wikipage.css
Labels: enhancement

#14 Updates on images and navigation bar
  WebPage/architecture.html
  WebPage/characteristics.html
  WebPage/deploymentModels.html
  WebPage/emergingTrends.html
  WebPage/history-1.html
  WebPage/images_alternative/concepts.jpeg
  WebPage/images_alternative/deployment.png
  WebPage/index.html
  WebPage/security.html
  WebPage/serviceModels.html
  WebPage/similarConcepts.html
Labels: enhancement

#15 Finished adding wikipedia text to the remaining pages
  WebPage/architecture.html
  WebPage/characteristics.html
  WebPage/deploymentModels.html
  WebPage/emergingTrends.html
  WebPage/history-1.html
  WebPage/index.html
  WebPage/serviceModels.html
  WebPage/similarConcepts.html
Labels: bug
